source "https://rubygems.org"

# Server
gem "sinatra"
gem 'shotgun'

# Config
gem 'require_all'

# Database
gem "pg"
gem "bunny", ">= 2.7.0"

group :development, :test do 
  gem "byebug"
end

group :test do
  gem "rspec"
  gem "rack-test"
end